# Generated by Django 3.2 on 2024-10-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20241016_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='genre',
        ),
    ]
