# Generated by Django 3.2 on 2024-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_category_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(max_length=5),
        ),
    ]
