# Generated by Django 3.2 on 2024-10-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20241016_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='category',
            new_name='categories',
        ),
    ]
