# Generated by Django 3.2 on 2024-10-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_rename_category_genre_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='categories',
        ),
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='reviews.category'),
            preserve_default=False,
        ),
    ]
