# Generated by Django 3.2 on 2024-10-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
